language: node_js
node_js:
  - 0.10
  - 4
  - 6
  - 7
  - 8
  - 9
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
script:
  - npm run ci && cat coverage/lcov.info | ./node_modules/.bin/jest --passWithNoTests && rm -rf coverage
